// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xyz.TForce.MiniCasher.Data.Migrations.Accounting;

namespace Xyz.TForce.MiniCasher.Data.Migrations.Accounting.firebird
{
    [DbContext(typeof(AccountingFirebirdSqlDbContext))]
    [Migration("00000000000001_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);
#pragma warning restore 612, 618
        }
    }
}
