using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Xyz.TForce.Data;

namespace Xyz.TForce.MiniCasher.Data.Repositories.Accounting.Entities.Specifications
{

  public class AccountEntitySpecification : IEntityTypeConfiguration<Account>
  {

    public void Configure(EntityTypeBuilder<Account> builder)
    {
      builder.MapToTable("Accounting_Accounts");
      builder.PrimaryKey(x => x.Id,isAutoGenerated: true);
      builder.Index(x => x.AccountId, name: "UX_AccountId", isUnique: true);
      builder.Index(x => x.AccountCode, name: "UX_AccountCode", isUnique: true);
      builder.MaxLength(x => x.AccountCode, ColumnLengths.KeyLength);
      builder.MaxLength(x => x.AccountName, ColumnLengths.KeyLength);
      builder.MaxLength(x => x.AccountDescription, ColumnLengths.SummaryLength);
      builder.RowVersion(x => x.MetaRowVersion);
    }
  }
}
